In [1]:
import pandas as pd 
import numpy as np 
import os

In [2]:
lib_path= os.path.join('data', 'libraries.csv')
state_path = os.path.join('data', 'states.csv')

In [3]:
raw_lib = pd.read_csv(lib_path)
raw_state = pd.read_csv(state_path)

/Users/linabattikha/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (2,17,18,19,20,21,22,23,24,25,26,27,28,29,30,34,35,36,37,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
raw_lib = (
    raw_lib[["State", 
             "Library ID", 
             "Library Name", 
             "City", "County", 
             "County Population" , 
             "Service Population",
            "Service Population Without Duplicates", 
            "Librarians", "Employees", "Total Staff", 
             "Print Collection", "Digital Collection", "Audio Collection", 
             "Downloadable Audio", "Physical Video", "Total Licensed Databases", 
             "Library Visits", "Registered Users"
            ]]
)

raw_lib.columns

'State', 'Library ID', 'Library Name', 'City', 'County',
       'County Population', 'Service Population',
       'Service Population Without Duplicates', 'Librarians', 'Employees',
       'Total Staff', 'Total Operating Revenue', 'Salaries',
       'Total Capital Revenue', 'Print Collection', 'Digital Collection',
       'Audio Collection', 'Downloadable Audio', 'Physical Video',
       'Total Licensed Databases', 'Library Visits', 'Registered Users'

In [5]:
raw_lib.head()

,State,Library ID,Library Name,City,County,County Population,Service Population,Service Population Without Duplicates,Librarians,Employees,Total Staff,Print Collection,Digital Collection,Audio Collection,Downloadable Audio,Physical Video,Total Licensed Databases,Library Visits,Registered Users
0,AK,AK0001,ANCHOR POINT PUBLIC LIBRARY,ANCHOR POINT,KENAI PENINSULA,57477,2059,2059,0.68,0,0.68,16843,0,258,0,4159,49,5379,396
1,AK,AK0002,ANCHORAGE PUBLIC LIBRARY,ANCHORAGE,ANCHORAGE,301010,300549,300549,29.1,49.8,78.9,481861,9773,28552,10496,63779,63,942873,119619
2,AK,AK0003,ANDERSON VILLAGE LIBRARY,ANDERSON,DENALI,1921,209,209,0.25,0.25,0.5,15304,0,48,0,1091,49,874,161
3,AK,AK0006,KUSKOKWIM CONSORTIUM LIBRARY,BETHEL,BETHEL,17868,6241,6241,1,2,3,34115,165,434,0,2345,187,44980,1500
4,AK,AK0007,BIG LAKE PUBLIC LIBRARY,BIG LAKE,MATANUSKA-SUSITNA,97882,12793,12793,1,2,3,23810,9773,1813,10496,2623,50,43285,3878

Employess --> the number of hours they employee (2.0 = 80 hours, so 2 full time or 4 part time)

librarians per 25,000 - service area ( probably don't need to convert) 

<a href= "https://www.imls.gov/sites/default/files/publications/documents/plsfy2014.pdf">link to dataset information</a>

In [6]:
ny_lib = raw_lib[raw_lib["State"] == "NY"]
ny_lib_new = ny_lib.copy()

# df is the cleaned frame to use
df = ny_lib_new.dropna() # removing all the null values 
cols = ['County Population', 'Service Population', 'Service Population Without Duplicates',
        'Librarians', 'Employees', 'Total Staff','Print Collection', 'Digital Collection', 'Audio Collection', 
        'Downloadable Audio', 'Physical Video', 'Total Licensed Databases', 'Library Visits', 'Registered Users']

# removing one row that had na values
df[cols] = df[cols].apply(pd.to_numeric,  errors='coerce',axis=1)
df.drop(df[df["County"] == '75'].index, inplace = True)

In [7]:
df

,State,Library ID,Library Name,City,County,County Population,Service Population,Service Population Without Duplicates,Librarians,Employees,Total Staff,Print Collection,Digital Collection,Audio Collection,Downloadable Audio,Physical Video,Total Licensed Databases,Library Visits,Registered Users
5680,NY,NY0001,MONTOUR FALLS MEMORIAL LIBRARY,MONTOUR FALLS,SCHUYLER,18479.0,1711.0,1698.0,1.31,0.15,1.46,11177.0,9549.0,171.0,2439.0,1218.0,17.0,11892.0,1013.0
5681,NY,NY0002,THE SOUTHWORTH LIBRARY ASSOCIATION,DRYDEN,TOMPKINS,104691.0,1889.0,1875.0,0.85,1.90,2.75,30641.0,5434.0,1093.0,2521.0,2084.0,22.0,45237.0,6026.0
5682,NY,NY0003,HILLVIEW FREE LIBRARY,DIAMOND POINT,WARREN,64973.0,400.0,397.0,0.76,0.00,0.76,13251.0,0.0,190.0,0.0,503.0,11.0,1313.0,314.0
5683,NY,NY0004,BROOKLYN PUBLIC LIBRARY,BROOKLYN,KINGS,2621793.0,2504700.0,2486292.0,272.13,505.31,777.44,2979810.0,99738.0,35540.0,13336.0,249408.0,90.0,8432208.0,1379710.0
5684,NY,NY0005,BUFFALO AND ERIE COUNTY PUBLIC LIBRARY,BUFFALO,ERIE,922835.0,919040.0,912286.0,60.45,172.01,232.46,1900180.0,34366.0,106366.0,7589.0,67253.0,60.0,1005375.0,83410.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6431,NY,NY9014,FALLSBURG LIBRARY,SOUTH FALLSBURG,SULLIVAN,75943.0,10674.0,10596.0,1.00,5.26,6.26,23457.0,5166.0,1059.0,2959.0,2821.0,24.0,31856.0,3768.0
6432,NY,NY9015,WESTERN SULLIVAN PUBLIC LIBRARY,JEFFERSONVILLE,SULLIVAN,75943.0,10576.0,10498.0,3.51,9.63,13.14,64242.0,5331.0,1616.0,2965.0,4699.0,26.0,58967.0,5170.0
6433,NY,NY9016,HAUPPAUGE PUBLIC LIBRARY,HAUPPAUGE,SUFFOLK,1502968.0,10936.0,10856.0,8.75,14.00,22.75,46531.0,96532.0,12044.0,16695.0,16519.0,55.0,140193.0,7715.0
6434,NY,NY9017,TOWN OF LAKE PLEASANT PUBLIC LIBRARY,SPECULATOR,HAMILTON,4715.0,781.0,775.0,0.88,0.65,1.53,13709.0,5148.0,986.0,2279.0,1678.0,12.0,10609.0,1625.0
6435,NY,NY9018,ALFRED BOX OF BOOKS LIBRARY,ALFRED,ALLEGANY,47736.0,5237.0,5199.0,0.88,0.88,1.76,10435.0,9549.0,755.0,2439.0,970.0,18.0,8988.0,1057.0

In [8]:
# retrieving the number of hours employees are working weekly - total 
df["Employees_Hours"] = df["Employees"]  * 40
df = df.rename(columns = {"Employees":"Employees_NC"}) #Not Converted

In [9]:
def get_dig_collection_libs(df): 
    dfc = df[df["Digital Collection"] > 0]
    return list(dfc["Library Name"])

def get_aud_collection_libs(df): 
    dfc = df[df["Audio Collection"] > 0]
    return list(dfc["Library Name"])

def get_down_collection_libs(df): 
    dfc = df[df["Downloadable Audio"] > 0]
    return list(dfc["Library Name"])

def get_pri_collection_libs(df): 
    dfc = df[df["Print Collection"] > 0]
    return list(dfc["Library Name"])

def get_pv_collection_libs(df): 
    dfc = df[df["Physical Video"] > 0]
    return list(dfc["Library Name"])

In [10]:
# DIGITAL COLLECTION 

# get all the digital collection libraries
dc = df.groupby("County").apply(get_dig_collection_libs).to_frame().reset_index()
# add in all the libraries within a county that have digital collection 
df = df.merge(dc, on = "County")

# rename columns so it has dc links
df.rename(columns = {0: "digital_collection_links"}, inplace = True)
# replace any row that has 0 for a colleciton with 0 digital links
df.loc[df["Digital Collection"] == 0, "digital_collection_links"] = 0

# removing self from list of links 
for row in df.itertuples():
    if row.digital_collection_links != 0:
        library = row._3
        digital_collection_links = list(row.digital_collection_links)
        digital_collection_links.remove(library)
        df.at[row.Index, 'digital_collection_links'] = digital_collection_links

In [11]:
# AUDIO COLLECTION 

# get all the audio collection libraries
ac = df.groupby("County").apply(get_aud_collection_libs).to_frame().reset_index()
# add in all the libraries within a county that have audio collection 
df = df.merge(ac, on = "County")

# rename columns so it has dc links
df.rename(columns = {0: "audio_collection_links"}, inplace = True)
# replace any row that has 0 for a colleciton with 0 digital links
df.loc[df["Audio Collection"] == 0, "audio_collection_links"] = 0

# removing self from list of links 
for row in df.itertuples():
    if row.audio_collection_links != 0:
        library = row._3
        audio_collection_links = list(row.audio_collection_links)
        audio_collection_links.remove(library)
        df.at[row.Index, 'audio_collection_links'] = audio_collection_links

In [12]:
# PRINT COLLECTION 

# get all the audio collection libraries
pc = df.groupby("County").apply(get_pri_collection_libs).to_frame().reset_index()
# add in all the libraries within a county that have print collection 
df = df.merge(pc, on = "County")

# rename columns so it has dc links
df.rename(columns = {0: "print_collection_links"}, inplace = True)
# replace any row that has 0 for a colleciton with 0 digital links
df.loc[df["Print Collection"] == 0, "print_collection_links"] = 0

# removing self from list of links 
for row in df.itertuples():
    if row.print_collection_links != 0:
        library = row._3
        print_collection_links = list(row.print_collection_links)
        print_collection_links.remove(library)
        df.at[row.Index, 'print_collection_links'] = print_collection_links

In [13]:
# DOWNLOADABLE COLLECTION 

# get all the audio collection libraries
downc = df.groupby("County").apply(get_down_collection_libs).to_frame().reset_index()
# add in all the libraries within a county that have print collection 
df = df.merge(downc, on = "County")

# rename columns so it has dc links
df.rename(columns = {0: "download_collection_links"}, inplace = True)
# replace any row that has 0 for a colleciton with 0 digital links
df.loc[df["Downloadable Audio"] == 0, "download_collection_links"] = 0

# removing self from list of links 
for row in df.itertuples():
    if row.download_collection_links != 0:
        library = row._3
        download_collection_links = list(row.download_collection_links)
        download_collection_links.remove(library)
        df.at[row.Index, 'download_collection_links'] = download_collection_links

In [14]:
# DOWNLOADABLE COLLECTION 

# get all the audio collection libraries
vc = df.groupby("County").apply(get_pv_collection_libs).to_frame().reset_index()
# add in all the libraries within a county that have print collection 
df = df.merge(vc, on = "County")

# rename columns so it has dc links
df.rename(columns = {0: "video_collection_links"}, inplace = True)
# replace any row that has 0 for a colleciton with 0 digital links
df.loc[df["Physical Video"] == 0, "video_collection_links"] = 0

# removing self from list of links 
for row in df.itertuples():
    if row.video_collection_links != 0:
        library = row._3
        video_collection_links = list(row.video_collection_links)
        video_collection_links.remove(library)
        df.at[row.Index, 'video_collection_links'] = video_collection_links

In [15]:
# add in a for loop for this 
df.loc[df["digital_collection_links"].str.len() == 0, "digital_collection_links"] = 0
df.loc[df["print_collection_links"].str.len() == 0, "print_collection_links"] = 0
df.loc[df["audio_collection_links"].str.len() == 0, "audio_collection_links"] = 0
df.loc[df["video_collection_links"].str.len() == 0, "video_collection_links"] = 0
df.loc[df["download_collection_links"].str.len() == 0, "download_collection_links"] = 0

In [16]:
df

,State,Library ID,Library Name,City,County,County Population,Service Population,Service Population Without Duplicates,Librarians,Employees_NC,...,Physical Video,Total Licensed Databases,Library Visits,Registered Users,Employees_Hours,digital_collection_links,audio_collection_links,print_collection_links,download_collection_links,video_collection_links
0,NY,NY0001,MONTOUR FALLS MEMORIAL LIBRARY,MONTOUR FALLS,SCHUYLER,18479.0,1711.0,1698.0,1.31,0.15,...,1218.0,17.0,11892.0,1013.0,6.0,"[DUTTON S. PETERSON MEMORIAL LIBRARY, WATKINS ...","[DUTTON S. PETERSON MEMORIAL LIBRARY, WATKINS ...","[DUTTON S. PETERSON MEMORIAL LIBRARY, WATKINS ...","[DUTTON S. PETERSON MEMORIAL LIBRARY, WATKINS ...","[DUTTON S. PETERSON MEMORIAL LIBRARY, WATKINS ..."
1,NY,NY0081,DUTTON S. PETERSON MEMORIAL LIBRARY,ODESSA,SCHUYLER,18479.0,2393.0,2375.0,0.55,0.00,...,855.0,18.0,10748.0,1238.0,0.0,"[MONTOUR FALLS MEMORIAL LIBRARY, WATKINS GLEN ...","[MONTOUR FALLS MEMORIAL LIBRARY, WATKINS GLEN ...","[MONTOUR FALLS MEMORIAL LIBRARY, WATKINS GLEN ...","[MONTOUR FALLS MEMORIAL LIBRARY, WATKINS GLEN ...","[MONTOUR FALLS MEMORIAL LIBRARY, WATKINS GLEN ..."
2,NY,NY0082,WATKINS GLEN CEN SCH DIS FREE PUB LIB,WATKINS GLEN,SCHUYLER,18479.0,8130.0,8070.0,1.35,1.20,...,1491.0,17.0,43035.0,7270.0,48.0,"[MONTOUR FALLS MEMORIAL LIBRARY, DUTTON S. PET...","[MONTOUR FALLS MEMORIAL LIBRARY, DUTTON S. PET...","[MONTOUR FALLS MEMORIAL LIBRARY, DUTTON S. PET...","[MONTOUR FALLS MEMORIAL LIBRARY, DUTTON S. PET...","[MONTOUR FALLS MEMORIAL LIBRARY, DUTTON S. PET..."
3,NY,NY0002,THE SOUTHWORTH LIBRARY ASSOCIATION,DRYDEN,TOMPKINS,104691.0,1889.0,1875.0,0.85,1.90,...,2084.0,22.0,45237.0,6026.0,76.0,"[GROTON PUBLIC LIBRARY, TOMPKINS COUNTY PUBLIC...","[GROTON PUBLIC LIBRARY, TOMPKINS COUNTY PUBLIC...","[GROTON PUBLIC LIBRARY, TOMPKINS COUNTY PUBLIC...","[GROTON PUBLIC LIBRARY, TOMPKINS COUNTY PUBLIC...","[GROTON PUBLIC LIBRARY, TOMPKINS COUNTY PUBLIC..."
4,NY,NY0159,GROTON PUBLIC LIBRARY,GROTON,TOMPKINS,104691.0,6024.0,5980.0,2.50,0.80,...,2273.0,22.0,23005.0,3621.0,32.0,"[THE SOUTHWORTH LIBRARY ASSOCIATION, TOMPKINS ...","[THE SOUTHWORTH LIBRARY ASSOCIATION, TOMPKINS ...","[THE SOUTHWORTH LIBRARY ASSOCIATION, TOMPKINS ...","[THE SOUTHWORTH LIBRARY ASSOCIATION, TOMPKINS ...","[THE SOUTHWORTH LIBRARY ASSOCIATION, TOMPKINS ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,NY,NY0760,WHITE PLAINS PUBLIC LIBRARY,WHITE PLAINS,WESTCHESTER,972634.0,56853.0,56435.0,17.68,25.38,...,21178.0,38.0,531300.0,37901.0,1015.2,"[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L..."
751,NY,NY0761,YONKERS PUBLIC LIBRARY,YONKERS,WESTCHESTER,972634.0,195976.0,194536.0,42.00,66.00,...,39805.0,73.0,860113.0,86269.0,2640.0,"[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L..."
752,NY,NY0762,JOHN C. HART MEMORIAL LIBRARY,SHRUB OAK,WESTCHESTER,972634.0,36081.0,35816.0,10.31,12.50,...,6849.0,23.0,212459.0,18798.0,500.0,"[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L...","[ARDSLEY PUBLIC LIBRARY, NORTH CASTLE PUBLIC L..."
753,NY,NY0778,"NEW YORK PUBLIC LIBRARY, THE BRANCH LIBRARIES",NEW YORK,NEW YORK,1636268.0,3439711.0,3414432.0,490.78,1962.77,...,831369.0,456.0,17729020.0,2495144.0,78510.8,0,0,0,0,0
754,NY,NY0794,CHEMUNG COUNTY LIBRARY DISTRICT,ELMIRA,CHEMUNG,87770.0,88830.0,88177.0,12.65,20.16,...,20171.0,23.0,318852.0,51287.0,806.4,0,0,0,0,0